#BSUB -P MED106
#BSUB -J mlp-sm-50
#BSUB -o logs/mlp-sm-50.o%J
#BSUB -e ERRORS-MLP-50
#BSUB -W 02:00
#BSUB -nnodes 1

cd /gpfs/alpine/world-shared/med106/yoonh/Benchmarks/Pilot3/JGH/CompressSM/MLP/

# data_dir: where is the data located
DATA=/gpfs/alpine/world-shared/med106/yoonh/storageFolder/Ensemble/RawLogits/276MtCnns/
# dump_dir: where the data is being dumped
DUMP=/gpfs/alpine/world-shared/med106/yoonh/storageFolder/RawLogits/MLP/P-50/
# prop: proportion of cases we are using
PROP=0.50
# offset: seed offset so we get different results
OFFSET=50

# module load cuda/11.4.0
module load ibm-wml-ce
conda activate jghs-ibm

jsrun -n5 -a1 -g1 -c7 python mlp-sm.py ${DATA} ${DUMP} ${PROP} ${OFFSET}